apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-webserver
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flask-webserver
  template:
    metadata:
      labels:
        app: flask-webserver
    spec:
      containers:
        - name: flask-webserver
          image: 352708296901.dkr.ecr.eu-north-1.amazonaws.com/{{IMG_NAME}}
---
apiVersion: v1
kind: Service
metadata:
  name: flask-webserver-service
spec:
  selector:
    app: flask-webserver
  ports:
    - port: 8080
      targetPort: 8080
